parapluu/Concuerror

Makefile
src/concuerror_options.erl

Add some basic defaults if missing, before finalization.

Fix use from an Erlang shell

---

src/concuerror_logger.erl
src/concuerror_options.erl
tests-real/suites/options/option-tests

It can be the case that the module is specified in the path.

Load path options before checking module options

---

Makefile
src/concuerror
tests-real/suites/options/Makefile
tests-real/suites/options/option-tests
tests-real/suites/options/other-tests

Another round  without moving anything.

Make symlinks work

---

src/concuerror_callback.erl
src/concuerror_scheduler.erl
tests/suites/corner_tests/results/deliver_exhaustive-test-inf-nodpor.txt
tests/suites/corner_tests/src/deliver_exhaustive.erl

Repository: https://github.com/aronisstav/erlang-concurrency-litmus-tests

Fixes inspired by aronisstav/erlang-concurrency-litmus-tests

---

.travis.yml
src/concuerror_callback.erl
tests/suites/basic_tests/results/message_queue_length-test-inf-optimal.txt
tests/suites/basic_tests/src/message_queue_length.erl

Fix https://github.com/parapluu/Concuerror/issues/157

Handle erlang:process_info(Pid, message_queue_length)

---

.travis.yml
Makefile
cover/cover-report
docs/index.md

Process cover results

---

src/concuerror.hrl
src/concuerror_callback.erl
src/concuerror_dependencies.erl
src/concuerror_options.erl
tests-real/suites/options/option3-tests
tests/suites/basic_tests/src/message_queue_length.erl

Process info fixes

---

.travis.yml
CONTRIBUTING.md
README.md

Fix badges on README.md

---

bin/concuerror
src/concuerror_callback.erl
tests/suites/basic_tests/results/system_info-test-inf-optimal.txt
tests/suites/basic_tests/src/inspect_system.erl
tests/suites/basic_tests/src/system_info.erl

Allow process_info calls for system processes

---

src/concuerror_callback.erl
src/concuerror_scheduler.erl
tests-real/suites/output/output-tests
tests-real/suites/output/src/harmless_exit.erl
tests-real/suites/poolboy/test

Abnormal exit signals that don't cause exits shouldn't lead to tips.

Fix abnormal signal tip emission point

---

CHANGELOG.md
src/average.erl
src/concuerror.erl
src/concuerror_estimator.erl
src/concuerror_logger.erl
src/concuerror_options.erl
src/concuerror_scheduler.erl
src/concuerror_window_average.erl
tests-real/suites/options/option3-tests
tests-real/suites/output/output-tests
tests-real/suites/output/src/many_scheds.erl

Improve the look of the progress bar and add total state space size and time to completion estimations.
Fixes #107.
Fixes #116.

New progress bar and space estimation

---

Makefile
tests-real/suites/makefile/makefile-tests
tests-real/suites/output/output-tests

Also fix a test that breaks on fast machines after merging #243.

Remove warnings_as_errors from default Makefile

---

src/concuerror_callback.erl
src/concuerror_dependencies.erl
src/concuerror_scheduler.erl
tests-real/suites/erlang-litmus/run_litmus.escript
tests/runtests.py
tests/suites/basic_tests/src/ets_new.erl

Fixes in preparation for OTP 21.
Fixes #245.

Some fixes for OTP 21

---

.travis.yml
src/concuerror_callback.erl
src/concuerror_dependencies.erl
tests-real/suites/gproc/test
tests/differ
tests/runtests.py
tests/scenarios.erl
tests/suites/basic_tests/results/monotonic_time-test-inf-optimal.txt
tests/suites/basic_tests/src/monotonic_time.erl
tests/suites/erlang_tests/results/erlang_timer-cancel_bad-inf-optimal.txt
tests/suites/erlang_tests/results/erlang_timer-cancel_badarg-inf-optimal.txt
tests/suites/erlang_tests/results/erlang_timer-read_bad-inf-optimal.txt
tests/suites/erlang_tests/results/erlang_timer-read_badarg-inf-optimal.txt
tests/suites/erlang_tests/src/erlang_timer.erl
tests/test_template.erl
tests/test_template_stripped.erl

Some useful parts from a yet-to-become-stable work-in-progress to support OTP 21...

Various fixes

---

src/concuerror_callback.erl
tests/suites/basic_tests/results/process_info-test3-inf-dpor.txt
tests/suites/basic_tests/src/process_info.erl

Fix result of process_info

---

src/concuerror.hrl
src/concuerror_callback.erl
src/concuerror_dependencies.erl
tests/suites/dpor_tests/results/process_info-links-inf-optimal.txt
tests/suites/dpor_tests/src/process_info.erl

Describe what will be improved after merging this Pull Request.

Fix dependency between process_info and link 

---

src/concuerror_estimator.erl
src/concuerror_logger.erl
test/concuerror_logger_tests.erl

Fixes aronisstav/Concuerror#45.

Make shown estimation prettier if < total

---

src/concuerror_callback.erl
src/concuerror_instrumenter.erl
tests-real/suites/options/header
tests-real/suites/output/output-tests
tests/suites/basic_tests/results/bad_dictionary-bad_erase-inf-optimal.txt
tests/suites/basic_tests/results/bad_dictionary-bad_get-inf-optimal.txt
tests/suites/basic_tests/results/bad_dictionary-bad_put-inf-optimal.txt
tests/suites/basic_tests/results/hibernate-test-inf-optimal.txt
tests/suites/basic_tests/src/bad_dictionary.erl
tests/suites/basic_tests/src/hibernate.erl

Increase coverage

---

src/concuerror_options.erl
tests/suites/basic_tests/results/system_instant_delivery-test-inf-optimal.txt
tests/suites/basic_tests/results/system_non_instant_delivery-test-inf-optimal.txt
tests/suites/basic_tests/src/system_instant_delivery.erl
tests/suites/basic_tests/src/system_non_instant_delivery.erl

Tests for instant delivery when system processes are involved

---

src/concuerror.hrl
src/concuerror_callback.erl
src/concuerror_dependencies.erl
src/concuerror_logger.erl
src/concuerror_scheduler.erl

Cleanup macros and types in concuerror.hrl
Fixes aronisstav/Concuerror#44

Refactor concuerror.hrl

---

.travis.yml
.travis/travis_has_latest_otp_version

* Improve messages printed by travis_has_latest_otp_version

Updates for Travis scripts and versions

---

.travis.yml
docs/_config.yml
docs/_includes/head.html
docs/_layouts/page.html
docs/_layouts/post.html
docs/index.md

Improvements for homepage, and small optimizations for Travis.
Closes aronisstav/Concuerror#53.

Homepage improvements

---

src/concuerror_callback.erl

Remove spurious timeout

---

.travis.yml
README.md

This reverts commit 8b0bd5d1b7e32f0be87160e5d7d52a65e4153b32.

Revert "travis: Upgrade to 21.3"

---

.travis.yml
docs/Makefile
docs/_posts/2020-04-03-bounds.md
docs/assets/css/main.css
docs/publications.md

Add an article about bounds to the website

---

.github/codecov.yml
.github/workflows/tests.yml
.github/workflows/website.yml
README.md

Use newer versions of Github action related things.

Update Github actions

---

.github/workflows/tests.yml
.github/workflows/website.yml

* Run only website tests if only files in `docs` changed
* Run all workflows on the 1st of each month

Improve github actions

---

docs/README.md

Test for only triggering website tests when only docs change

Test for only triggering website tests when only docs change

---

README.md

Add link to hexdocs in repo page

Add link to Hex in README.md

---

.github/workflows/tests.yml
.github/workflows/website.yml

Fix breaking doc tests

---

.github/workflows/tests.yml

This should fix the monthly job.

Pin a rebar3 version since OTP 24 is deprecated in nightly

---

docs/Makefile

Describe what will be improved after merging this Pull Request.

Fix remote link checks

---

docs/_config.yml

Describe what will be improved after merging this Pull Request.

Remove google analytics
