parapluu/Concuerror

src/concuerror_callback.erl, tests/suites/basic_tests/results/inspect_system-test-inf-dpor.txt, tests/suites/basic_tests/src/inspect_system.erl
This patches the ugly crash reported in #48. Thanks to evnu for the report!
=> Emit an error message if process_info is asked for a system process

src/concuerror_callback.erl, src/concuerror_scheduler.erl
As the legends have it, concurrent programming is hard.
Concuerror would sometimes emit a 'process did not respond' error during exploration of the `advanced_tests/src/manolis/rush_hour:test_2workers_benchmark/0`, as his scheduler would get angry waiting for an event from the main process while the main process was apparently ALSO waiting for a request to send an event to the scheduler...
... this of course makes no sense but such are the joys of concurrent programming.
This patch is not a fix; the fix would entail properly synchronizing the offending events. For the time being, adding one more synchronization checkpoint is enough, nevertheless.
=> Refactor and synchronize resetting

src/concuerror.hrl, src/concuerror_instrumenter.erl, src/concuerror_loader.erl, tests-real/suites/options/other-tests, tests-real/suites/options/src/load_nif.erl, tests/suites/advanced_tests/src/send_order.erl
Stateless model checking requires that any state of the program
can reliably be reached just by making the
same scheduling choices. In order for this to work, one must control
all other sources of nondeterminism. NIFs cannot, in general, be
guaranteed to return the same result for each call with the same
arguments, nor can they be detected/intercepted.
With this patch Concuerror emits a warning when
instrumenting modules that may try to load NIFs.
Fixes #77.
=> Warn when instrumenting modules with calls to erlang:load_nif/2

.travis.yml, .travis/travis_has_latest_otp_version
This PR will be rebased after Travis properly supports 20.3 to check intended behaviour before being merged.
=> Travis fixes

CHANGELOG.md, src/concuerror_callback.erl, src/concuerror_dependencies.erl, src/concuerror_io_lib.erl, src/concuerror_logger.erl, src/concuerror_scheduler.erl, tests-real/suites/options/other-tests, tests-real/suites/options/src/deadlock.erl
- Show mailbox contents on deadlocks
- Use process_info(_, current_stacktrace) to retrieve stacktraces
- Generalize support for group_leader (in OTP 21 it belongs to erts_internal)
=> Show mailbox contents on deadlock (and other minor)

CHANGELOG.md, src/concuerror.hrl, src/concuerror_dependencies.erl, src/concuerror_options.erl, tests-real/suites/erlang-litmus/.gitignore, tests-real/suites/erlang-litmus/Makefile, tests-real/suites/erlang-litmus/run_litmus.escript, tests-real/suites/erlang-litmus/test, tests/suites/basic_tests/results/group_leader3-test-inf-dpor.txt, tests/suites/basic_tests/src/group_leader3.erl
Start using the aronisstav/erlang-concurrency-litmus-tests repository as a source of tests
Fixes #135.
* Litmus tests are failing to compile in 17 and earlier because `assert.hrl` was not yet independent from `eunit.hrl`.
=> Add erlang-concurrency-litmus-tests as a testsuite

CHANGELOG.md, src/concuerror.hrl, src/concuerror_callback.erl, src/concuerror_dependencies.erl, src/concuerror_logger.erl, src/concuerror_options.erl, tests-real/suites/options/option3-tests, tests-real/suites/options/src/register.erl, tests-real/suites/poolboy/test, tests/suites/basic_tests/results/process_info-test2-inf-dpor.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-0-dpor.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-0.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-1-dpor.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-1.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-inf-dpor.txt, tests/suites/basic_tests/results/sched_tests-test_send_3-inf.txt, tests/suites/basic_tests/src/process_info.erl, tests/suites/basic_tests/src/sched_tests.erl
* List processes with their registered name
* Fix erlang:send/3 return value
* Add support for erlang:process_info/2 with a list argument
**Important**: the new test for `process_info/2` is currently broken. I get this output when running it, and I don't know how to fix it:
```
* The following pair of instructions is not explicitly marked as non-racing in Concuerror's internals:
1) [{registered_name,[]},{group_leader,<0.74.0>}] = erlang:process_info(<0.85.0>, [registered_name,group_leader])
2) true = erlang:register(foo, <0.85.0>)
Please notify the developers to add info about this pair.
You can run without '--assume_racing false' to treat them as racing.
[{concuerror_dependencies,dependent_process_info,
[{builtin_event,<0.82.0>,undefined,false, …
```
=> Assorted improvements

tests-real/suites/erlang-litmus/run_litmus.escript
A build on master was hanging with the previous 2 limit. Increase it "arbitrarily" to a value that works.
=> Increase litmus concurrency limit

CHANGELOG.md, src/concuerror.erl, src/concuerror.hrl, src/concuerror_logger.erl, src/concuerror_options.erl, src/concuerror_scheduler.erl, tests-real/suites/options/option3-tests, tests-real/suites/options/src/first_and_other_deadlock.erl, tests-real/suites/options/src/other_deadlock.erl
Add option to report only the errors involving the first process.
=> Add option to report only the errors involving the first process

src/concuerror_dependencies.erl, tests/suites/basic_tests/results/ets_select-match_against_different_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_against_different_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_against_different_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_against_matching_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_against_matching_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_against_matching_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_different_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_different_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_different_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_matching_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_matching_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-match_object_against_matching_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_different_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_different_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_different_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_matching_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_matching_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_against_matching_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_different_any-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_different_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_different_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_different_tuples-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_matching_any-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_matching_keys-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_matching_matchspec-inf-dpor.txt, tests/suites/basic_tests/results/ets_select-select_delete_against_matching_tuples-inf-dpor.txt, tests/suites/basic_tests/src/ets_select.erl
An ets operation using a match spec (such as `match`, `select` or `select_delete`) depends only with ets operations modifying matching tuples, or with ets operations where the tuples are not known.
It would be possible to further improve the dependency tests between a match spec using ets operation and an operation where only the key is known by reducing the match spec to the key field only. But this is not yet implemented.
=> Refine dependencies of ets operations using a match spec

src/concuerror_dependencies.erl, src/concuerror_logger.erl, tests/suites/basic_tests/results/ets_unguarded-test-inf-optimal.txt, tests/suites/basic_tests/src/ets_unguarded.erl
Race info printing was messed up when the order of printing error traces and race analysis was changed. This fixes the shown info.
A small bug in the dependencies of ETS insert is also fixed.
=> Fix race info printing

src/concuerror.hrl, src/concuerror_callback.erl, tests/suites/basic_tests/results/ets_info-info_bad-inf-optimal.txt, tests/suites/basic_tests/results/ets_info-info_badarg-inf-optimal.txt, tests/suites/basic_tests/results/ets_info-info_good-inf-optimal.txt, tests/suites/basic_tests/results/ets_info-info_system-inf-optimal.txt, tests/suites/basic_tests/src/ets_info.erl
In OTP 20 ETS identifiers changed to references.
=> Fix ETS TIDs in OTP 20

.travis/after_success, .travis/before_script
Due to recent changes in covertool, coverage reports stopped being generated. This PR fixes this and locks a working version so that this doesn't break again unexpectedly.
=> Fix coverage

CHANGELOG.md, src/concuerror_callback.erl, src/concuerror_inspect.erl, tests-real/suites/options/header, tests-real/suites/output/output-tests, tests-real/suites/output/src/more_stacktrace.erl
The patch c95c2c6 made it possible for stacktraces to linger and be reported when they were irrelevant. This patch fixes this.
Fixes aronisstav/Concuerror#42.
=> Fix stacktraces

CHANGELOG.md, src/concuerror.erl, src/concuerror_callback.erl, src/concuerror_dependencies.erl, src/concuerror_instrumenter.erl, tests/suites/basic_tests/results/process_info-test_message_queue_len-inf-dpor.txt, tests/suites/basic_tests/results/process_info-test_messages-inf-dpor.txt, tests/suites/basic_tests/results/process_info-test_mql_flush-inf-dpor.txt, tests/suites/basic_tests/results/safeops_coverage-test-inf-optimal.txt, tests/suites/basic_tests/src/process_info.erl, tests/suites/basic_tests/src/safeops_coverage.erl
More accurate dependencies of message queue info ops, but some degradation as the `message` item should normally be an observer of message delivery races. As this is too complex right now, it was degraded instead.
=> Fix dependencies of process_info(..., message*)

src/concuerror_options.erl
Detected by what I presume must be an updated version of one of the tools run during building. The particular run that caught this was an automatic periodic build by Travis CI.  Yay!
=> Fix documentation link

src/concuerror_dependencies.erl, tests/suites/basic_tests/results/ets_delete_2-ets_delete_2_twice-inf-dpor.txt, tests/suites/basic_tests/src/ets_delete_2.erl
The infinite loop occurs because
concuerror_dependencies:dependent_built_in
did not differentiate between ets:delete/1
and ets:delete/2 in the clause this commit fixes.
Fix for https://github.com/parapluu/Concuerror/issues/314
Also see that same ticket for comments about the `ets_delete_2` test which doesn't seem to test what it's supposed to.
Same question about CHANGELOG, should it be updated?
=> Fix infinite loop when two processes call ets:delete/2

src/concuerror_instrumenter.erl, tests/suites/erlang_tests/results/erlang_maps-maps_fold-inf-optimal.txt, tests/suites/erlang_tests/src/erlang_maps.erl
This is used by maps:fold/3 and others to walk through maps.
Fix for https://github.com/parapluu/Concuerror/issues/313
Should it update the CHANGELOG?
=> Add erts_internal:maps_next/3 to safe functions

.github/workflows/website.yml, docs/index.md
Travis is changing its model and might be tricky to maintain. Let's try Github Actions.
=> Migrate from Travis to GitHub Actions

.github/workflows/tests.yml
Pin the lint and dialyzer actions to latest actually supported version.
Fixes a problem with parapluu/Concuerror#330.
=> Pin container version 23

docs/Makefile, docs/_posts/2014-06-03-poolboy-example-errors.md, docs/faq.md
Fix checks in tests-external doc target
=> Docs fixes

src/concuerror_callback.erl
Prior to this fix the mock for that function would fail with `badarg` because it was translated to
`ets:lookup_element(?persistent_term, 2, Key)` instead of 
`ets:lookup_element(?persistent_term, Key, 2)`.
https://www.erlang.org/doc/apps/stdlib/ets.html#lookup_element/3
=> Fix persistent_term:get/1 builtin.
